// This file is auto-generated by shader-minifier plugin. Do not edit directly.
// Generated with Shader Minifier 1.5.1 (https://github.com/laurentlb/Shader_Minifier/)
export const A_COLOR = "z"
export const A_NORMAL = "r"
export const A_POSITION = "f"
export const A_TEXCOORD = "d"
export const A_WORLDMATRIX = "m"
export const OUTPUTCOLOR = "i"
export const U_AMBIENTLIGHT = "E"
export const U_BLOOMTEXTURE = "w"
export const U_CAMERAPOSITION = "l"
export const U_COLORTEXTURE = "n"
export const U_DEPTHTEXTURE = "y"
export const U_ITERATION = "p"
export const U_LIGHTDIRECTION = "D"
export const U_LIGHTPOSITION = "x"
export const U_PROJECTIONMATRIX = "v"
export const U_SHADOWMAPMATRIX = "c"
export const U_VIEWMATRIX = "t"
export const V_COLOR = "o"
export const V_NORMAL = "u"
export const V_POSITION = "s"
export const V_SHADOWMAPTEXCOORD = "g"
export const V_TEXCOORD = "e"

export const SHADOW_VERT = `#version 300 es
precision mediump float;in vec4 f;layout(location=3)in mat4 m;uniform mat4 v,t;void main(){gl_Position=v*t*m*f;}`

export const SHADOW_FRAG = `#version 300 es
precision mediump float;out vec4 i;void main(){i=vec4(1);}`

export const POST_VERT = `#version 300 es
precision mediump float;in vec2 f,d;out vec2 e;void main(){gl_Position=vec4(f,0,1);e=d;}`

export const POST_FRAG = `#version 300 es
precision mediump float;uniform sampler2D n,w;in vec2 e;out vec4 i;void main(){vec4 m=texture(w,e);i=vec4(texture(n,e).xyz+2.f*m.w*m.xyz,1);}`

export const MAIN_VERT = `#version 300 es
precision mediump float;in vec4 f,z,r;in mat4 m;uniform mat4 v,t,c;out vec4 s,u,o,g;void main(){s=m*f;u=transpose(inverse(m))*r*-1.f;o=z;g=c*s;gl_Position=v*t*s;}`

export const MAIN_FRAG = `#version 300 es
precision mediump float;uniform vec3 l,x,D;uniform sampler2D y;uniform float E;in vec4 o,s,u,g;out vec4 i;void main(){if(o.x>.99f||o.y>.99f||o.z>.99f){i=o;return;}vec3 m=normalize(u.xyz),n=g.xyz/g.w;float v=n.z-1e-4f,f=0.f,e=0.f;for(int m=-2;m<=2;m++)for(int i=-2;i<=2;i++){vec4 s=texture(y,n.xy+vec2(i,m)/1024.f);if(s.x<=v)e+=1.f;f+=1.f;}vec3 z=s.xyz-x,d=normalize(s.xyz-x);v=dot(z,z);float t=0.f;if(n.x>=0.f&&n.x<=1.f&&n.y>=0.f&&n.y<=1.f&&(v<16e2f&&dot(d,normalize(D))>.9f)){float m=1.f-e/f;t=m*(1.f/(1.f+.001f*sqrt(v)+3e-4f*v));}v=clamp(E*max(0.f,dot(normalize(s.xyz-vec3(256,256,-128)),m))+(1.2f-E)*max(0.f,dot(d,m))*t,0.f,1.f);z=mix(vec3(0),o.xyz,v);t*=pow(max(dot(normalize(l-s.xyz),reflect(d,m)),0.f),64.f);z=mix(z,vec3(1),t);i=vec4(z.xyz,o.w);}`

export const BLOOM_VERT = `#version 300 es
precision mediump float;in vec2 f,d;out vec2 e;void main(){gl_Position=vec4(f,0,1);e=d;}`

export const BLOOM_FRAG = `#version 300 es
precision mediump float;uniform sampler2D n;uniform int p;in vec2 e;out vec4 i;float B[11]=float[11](.01f,.02f,.04f,.08f,.16f,.38f,.16f,.08f,.04f,.02f,.01f);void main(){if(p==0){vec4 m=texture(n,e);if(max(m.x,max(m.y,m.z))>.99f)i=m;else discard;}else{vec4 m=vec4(0);float f=0.f;for(int v=-5;v<=5;v++){vec2 i=p%2==1?vec2(float(v)/512.f,0):vec2(0,float(v)/512.f);vec4 s=texture(n,e+i);m.xyz+=B[v+5]*s.xyz*s.w;f+=B[v+5]*s.w;}i=f==0.f?vec4(0,0,0,1):vec4(m.xyz/f,f);}}`

